---
name: srt-reader
services:
  php:
    build:
      dockerfile: ./development/containers/php/Dockerfile
      context: ./../
      target: develop
      args:
        UID: 1001
        GID: 1001
      provenance: false
      sbom: false
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    read_only: true
    init: true
    tty: true
    configs:
      - source: php_xdebug
        target: /usr/local/etc/php/conf.d/xdebug.ini
        uid: '1001'
        gid: '1001'
        mode: 0400
    volumes:
      - ./../:/home/php/app
      - ./../tmp/composer:/home/php/.composer
    tmpfs:
      - /tmp
      - /run
    ports:
      - '127.0.0.1:9009:9009'

configs:
  php_xdebug:
    file: ./containers/php/xdebug.ini
