---

x-php: &service-php
  build: &service-php-build
    dockerfile: ./development/containers/php/Dockerfile
    context: .
    target: base
    args:
      UID: 1001
      GID: 1001
    x-bake:
      output:
        - type=docker
    cache_from:
      - type=gha
    cache_to:
      - type=gha,mode=max
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges=true
  read_only: true
  user: 1001:1001
  volumes:
    - ./../source:/home/php/app/source:read-only
    - ./../tests:/home/php/app/tests:read-only
    - ./../Makefile:/home/php/app/Makefile:read-only
  tmpfs:
    - /tmp
    - /run

name: srt-reader
services:
  tests-runner-integration:
    <<: *service-php
    build:
      <<: *service-php-build
      target: tests-runner-integration
      tags:
        - srt-reader-tests-runner-integration:latest

  tests-runner-unit:
    <<: *service-php
    build:
      <<: *service-php-build
      target: tests-runner-unit
      tags:
        - srt-reader-tests-runner-unit:latest

  psalm:
    <<: *service-php
    build:
      <<: *service-php-build
      target: psalm
      tags:
        - srt-reader-psalm:latest
    volumes:
      - ./../development:/home/php/app/development
      - ./../grammar:/home/php/app/grammar:read-only
      - ./../source:/home/php/app/source:read-only
      - ./../tests:/home/php/app/tests:read-only
      - ./../Makefile:/home/php/app/Makefile:read-only

  php-cs-fixer:
    <<: *service-php
    build:
      <<: *service-php-build
      target: php-cs-fixer
      tags:
        - srt-reader-php-cs-fixer:latest
    environment:
      GITHUB_ACTIONS: ${GITHUB_ACTIONS:-false}
    volumes:
      - ./../development:/home/php/app/development
      - ./../grammar:/home/php/app/grammar:read-only
      - ./../source:/home/php/app/source:read-only
      - ./../tests:/home/php/app/tests:read-only
      - ./../Makefile:/home/php/app/Makefile:read-only
      - ./../composer.json:/home/php/app/composer.json:read-only
      - ./../composer.lock:/home/php/app/composer.lock:read-only
