---
services:
  php:
    build:
      dockerfile: ./development/php/Dockerfile
      context: ./../
      target: develop
      provenance: false
      sbom: false
    init: true
    tty: true
    volumes:
      - ./../:/root/app
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    ports:
      - '127.0.0.1:9009:9009'
