---
services:
  tests-runner:
    build:
      context:  ./../
      dockerfile: ./development/php/tests.Dockerfile
    tty: true
    volumes:
      - ./../:/root/app
      - ./../tmp/composer:/root/.composer
