---
services:
  tests-runner:
    build:
      dockerfile: ./development/php/Dockerfile
      context: .
      target: base
      x-bake:
        output:
          - type=docker
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    init: true
    tty: true
    volumes:
      - ./../:/root/app
      - ./../tmp/composer:/root/.composer
