---

x-php-build: &service-php-build
  dockerfile: ./development/php/Dockerfile
  context: .
  target: base
  args:
    UID: 1001
    GID: 1001
  x-bake:
    output:
      - type=docker
  cache_from:
    - type=gha
  cache_to:
    - type=gha,mode=max

x-php: &service-php
  build:
    <<: *service-php-build
  cap_drop:
    - ALL
  security_opt:
    - no-new-privileges=true
  read_only: true
  init: true
  tty: true
  user: 1001:1001
  volumes:
    - ./../source:/home/php/app/source:read-only
    - ./../tests:/home/php/app/tests:read-only
    - ./../Makefile:/home/php/app/Makefile:read-only
  tmpfs:
    - /tmp
    - /run

name: srt-reader
services:
  tests-runner-integration:
    <<: *service-php
    build:
      <<: *service-php-build
      target: tests-runner-integration
      tags:
        - srt-reader-tests-runner-integration:latest

  tests-runner-unit:
    <<: *service-php
    build:
      <<: *service-php-build
      target: tests-runner-unit
      tags:
        - srt-reader-tests-runner-unit:latest
